name: right_code_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_bottom_navigation_bar: ^1.3.3
  reactive_forms: ^17.0.1
  flutter_hooks: ^0.20.5
  icons_plus: ^5.0.0
  persistent_bottom_nav_bar: ^6.0.0
  flutter_rounded_date_picker: ^3.0.4
  intl: ^0.19.0
  supabase_flutter: ^2.5.8
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_riverpod: ^2.5.1
  one_context: ^4.0.0
  dartz: ^0.10.1
  file_picker: ^8.0.6
  uuid: ^4.4.2
  simple_chips_input: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: any
  build_runner: any
  json_serializable: any

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
